---
- name: Setup Prometheus on GCP VM
  hosts: node-1
  become: yes
  vars:
    prometheus_version: "2.47.1"
    prometheus_dir: "/etc/prometheus"
    prometheus_data_dir: "/var/lib/prometheus"
    prometheus_user: "prometheus"

  tasks:
    - name: Create prometheus user
      user:
        name: "{{ prometheus_user }}"
        shell: /bin/false

    - name: Download Prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: "/tmp/prometheus-{{ prometheus_version }}.tar.gz"
        mode: '0755'

    - name: Extract Prometheus
      unarchive:
        src: "/tmp/prometheus-{{ prometheus_version }}.tar.gz"
        dest: "/tmp/"
        remote_src: yes

    - name: Copy Prometheus binaries
      copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus"
        dest: "/usr/local/bin/prometheus"
        mode: '0755'
        remote_src: yes

    - name: Copy Prometheus configuration file
      copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/promtool"
        dest: "/usr/local/bin/promtool"
        mode: '0755'
        remote_src: yes

    - name: Create directories for Prometheus
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_user }}"
        mode: '0755'
      loop:
        - "{{ prometheus_dir }}"
        - "{{ prometheus_data_dir }}"

    - name: Copy Prometheus config file
      copy:
        dest: "{{ prometheus_dir }}/prometheus.yml"
        content: |
          global:
            scrape_interval: 15s

          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']

            - job_name: 'node_exporter'
              static_configs:
                - targets: ['localhost:9100']

            - job_name: 'remote_servers'
              static_configs:
                - targets:
                  - '34.72.161.125:9100'
                  - '35.188.169.92:9100'
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_user }}"
        mode: '0644'

    - name: Create systemd service for Prometheus
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=prometheus
          ExecStart=/usr/local/bin/prometheus --config.file={{ prometheus_dir }}/prometheus.yml --storage.tsdb.path={{ prometheus_data_dir }}
          Restart=always

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: '0644'
      notify:
        - Reload systemd

    - name: Start and enable Prometheus service
      systemd:
        name: prometheus
        enabled: yes
        state: started

  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes
